### ISSUE TITLE
No

### ISSUE THREAD

**Issue by tpoisot** [viralemergence/tiktok#1]
:man_dancing:  stop :man_dancing:

**Comment by cjcarlson** [comment]
Thanks!

**Comment by tpoisot** [comment]
> And I step outside
And I take a deep breath and I get real high
And I scream from the top of my lungs,
🕺 stop 🕺

**Comment by tpoisot** [comment]
🙂

**Comment by cjcarlson** [comment]
I am scared. Tim wins.

**Comment by tpoisot** [comment]
There was a smol prof from Georgetown
Who GitHub'd about tiktok like a clown
He thought the issue locked
And so the problem solved
But @tpoisot is admin and wreak'th havoc
